# Light Chaos Monkey Excpetion Assault Handler Configuration.

# Enable the handler if set to true. Otherwise, the request will passthrough.
enabled: true
# How many requests are to be attacked. 1 each request, 5 each 5th request is attacked
level: 10
